/*
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.parser.antlr;

import com.google.inject.Inject;
import edu.aut.islab.ghaemi.minuy.parser.antlr.internal.InternalMyUiDslParser;
import edu.aut.islab.ghaemi.minuy.services.MyUiDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyUiDslParser extends AbstractAntlrParser {

	@Inject
	private MyUiDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyUiDslParser createParser(XtextTokenStream stream) {
		return new InternalMyUiDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MyUiDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyUiDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
