/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.scoping;

import edu.aut.islab.ghaemi.minuy.scoping.AbstractMyUiDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MyUiDslScopeProvider extends AbstractMyUiDslScopeProvider {
}
