/*
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.ui;

import com.google.inject.Injector;
import edu.aut.islab.ghaemi.minuy.ui.internal.MinuyActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyUiDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MinuyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MinuyActivator.getInstance().getInjector(MinuyActivator.EDU_AUT_ISLAB_GHAEMI_MINUY_MYUIDSL);
	}
	
}
