/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.ui;

import edu.aut.islab.ghaemi.minuy.ui.AbstractMyUiDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyUiDslUiModule extends AbstractMyUiDslUiModule {
  public MyUiDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
