/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.myUiDsl.impl;

import edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Aval;
import edu.aut.islab.ghaemi.minuy.myUiDsl.BackColor;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Body;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Border;
import edu.aut.islab.ghaemi.minuy.myUiDsl.BorderRad;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Bval;
import edu.aut.islab.ghaemi.minuy.myUiDsl.ClassName;
import edu.aut.islab.ghaemi.minuy.myUiDsl.ClassNameSec;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Clr;
import edu.aut.islab.ghaemi.minuy.myUiDsl.ClrVals;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Color;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Coord;
import edu.aut.islab.ghaemi.minuy.myUiDsl.CssStyle;
import edu.aut.islab.ghaemi.minuy.myUiDsl.CssStyles;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Disp;
import edu.aut.islab.ghaemi.minuy.myUiDsl.DispVals;
import edu.aut.islab.ghaemi.minuy.myUiDsl.DownAspect;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Flt;
import edu.aut.islab.ghaemi.minuy.myUiDsl.FltVals;
import edu.aut.islab.ghaemi.minuy.myUiDsl.FourAspect;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Gval;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Head;
import edu.aut.islab.ghaemi.minuy.myUiDsl.InnerClass;
import edu.aut.islab.ghaemi.minuy.myUiDsl.InnerFeature;
import edu.aut.islab.ghaemi.minuy.myUiDsl.InnerStyle;
import edu.aut.islab.ghaemi.minuy.myUiDsl.InnerText;
import edu.aut.islab.ghaemi.minuy.myUiDsl.InnerType;
import edu.aut.islab.ghaemi.minuy.myUiDsl.InnerTypeArray;
import edu.aut.islab.ghaemi.minuy.myUiDsl.LeftAspect;
import edu.aut.islab.ghaemi.minuy.myUiDsl.LiteralColor;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Marg;
import edu.aut.islab.ghaemi.minuy.myUiDsl.MaxVal;
import edu.aut.islab.ghaemi.minuy.myUiDsl.MidVal;
import edu.aut.islab.ghaemi.minuy.myUiDsl.MinMaxValue;
import edu.aut.islab.ghaemi.minuy.myUiDsl.MinVal;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Model;
import edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslFactory;
import edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Node;
import edu.aut.islab.ghaemi.minuy.myUiDsl.OFlow;
import edu.aut.islab.ghaemi.minuy.myUiDsl.OFlowVals;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Padd;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Pos;
import edu.aut.islab.ghaemi.minuy.myUiDsl.PosVals;
import edu.aut.islab.ghaemi.minuy.myUiDsl.RgbaColor;
import edu.aut.islab.ghaemi.minuy.myUiDsl.RightAspect;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Rval;
import edu.aut.islab.ghaemi.minuy.myUiDsl.SelfRepeat;
import edu.aut.islab.ghaemi.minuy.myUiDsl.UpAspect;
import edu.aut.islab.ghaemi.minuy.myUiDsl.VerAl;
import edu.aut.islab.ghaemi.minuy.myUiDsl.VeralVals;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Wid;
import edu.aut.islab.ghaemi.minuy.myUiDsl.colorDef;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyUiDslPackageImpl extends EPackageImpl implements MyUiDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass headEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass bodyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nodeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass selfRepeatEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass accessoryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass innerFeatureEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass innerTextEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass innerStyleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass innerClassEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass classNameEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass classNameSecEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass innerTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cssStylesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cssStyleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass borderEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass colorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass backColorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass colorDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass literalColorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rgbaColorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rvalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass gvalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass bvalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass avalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass borderRadEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass posEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fltEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass clrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dispEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass verAlEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass oFlowEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass widEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass h8EClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass coordEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass margEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass paddEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass minMaxValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass minValEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass maxValEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass midValEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fourAspectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass leftAspectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rightAspectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass upAspectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass downAspectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum posValsEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum fltValsEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum clrValsEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum dispValsEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum veralValsEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum oFlowValsEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum innerTypeArrayEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MyUiDslPackageImpl()
  {
    super(eNS_URI, MyUiDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link MyUiDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MyUiDslPackage init()
  {
    if (isInited) return (MyUiDslPackage)EPackage.Registry.INSTANCE.getEPackage(MyUiDslPackage.eNS_URI);

    // Obtain or create and register package
    MyUiDslPackageImpl theMyUiDslPackage = (MyUiDslPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof MyUiDslPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new MyUiDslPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theMyUiDslPackage.createPackageContents();

    // Initialize created meta-data
    theMyUiDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMyUiDslPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MyUiDslPackage.eNS_URI, theMyUiDslPackage);
    return theMyUiDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Heads()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Bodis()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Accessories()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getHead()
  {
    return headEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getHead_FileName()
  {
    return (EAttribute)headEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getHead_HeadType()
  {
    return (EAttribute)headEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBody()
  {
    return bodyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBody_Name()
  {
    return (EReference)bodyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBody_Right()
  {
    return (EReference)bodyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBody_SelfRepeat()
  {
    return (EReference)bodyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getNode()
  {
    return nodeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getNode_Name()
  {
    return (EAttribute)nodeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSelfRepeat()
  {
    return selfRepeatEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSelfRepeat_Number()
  {
    return (EAttribute)selfRepeatEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSelfRepeat_Vertical()
  {
    return (EAttribute)selfRepeatEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAccessory()
  {
    return accessoryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAccessory_Left()
  {
    return (EReference)accessoryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAccessory_Text()
  {
    return (EReference)accessoryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAccessory_Style()
  {
    return (EReference)accessoryEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAccessory_Clazz()
  {
    return (EReference)accessoryEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAccessory_Type()
  {
    return (EReference)accessoryEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAccessory_Feature()
  {
    return (EReference)accessoryEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInnerFeature()
  {
    return innerFeatureEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getInnerFeature_Value()
  {
    return (EAttribute)innerFeatureEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInnerText()
  {
    return innerTextEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getInnerText_Value()
  {
    return (EAttribute)innerTextEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInnerStyle()
  {
    return innerStyleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getInnerStyle_Styles()
  {
    return (EReference)innerStyleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInnerClass()
  {
    return innerClassEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getInnerClass_Clazzes()
  {
    return (EReference)innerClassEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getClassName()
  {
    return classNameEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getClassName_TheId()
  {
    return (EAttribute)classNameEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getClassName_Clazz()
  {
    return (EReference)classNameEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getClassNameSec()
  {
    return classNameSecEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getClassNameSec_CfClazz()
  {
    return (EAttribute)classNameSecEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInnerType()
  {
    return innerTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getInnerType_Value()
  {
    return (EAttribute)innerTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCssStyles()
  {
    return cssStylesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCssStyles_Styles()
  {
    return (EReference)cssStylesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCssStyle()
  {
    return cssStyleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBorder()
  {
    return borderEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBorder_Value()
  {
    return (EReference)borderEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getColor()
  {
    return colorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getColor_Value()
  {
    return (EReference)colorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBackColor()
  {
    return backColorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBackColor_Value()
  {
    return (EReference)backColorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getcolorDef()
  {
    return colorDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getLiteralColor()
  {
    return literalColorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getLiteralColor_Value()
  {
    return (EAttribute)literalColorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRgbaColor()
  {
    return rgbaColorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRgbaColor_Rval()
  {
    return (EReference)rgbaColorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRgbaColor_Gval()
  {
    return (EReference)rgbaColorEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRgbaColor_Bval()
  {
    return (EReference)rgbaColorEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRgbaColor_Aval()
  {
    return (EReference)rgbaColorEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRval()
  {
    return rvalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRval_Value()
  {
    return (EAttribute)rvalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGval()
  {
    return gvalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGval_Value()
  {
    return (EAttribute)gvalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBval()
  {
    return bvalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBval_Value()
  {
    return (EAttribute)bvalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAval()
  {
    return avalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAval_Value()
  {
    return (EAttribute)avalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBorderRad()
  {
    return borderRadEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBorderRad_Value()
  {
    return (EAttribute)borderRadEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBorderRad_MeasureType()
  {
    return (EAttribute)borderRadEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPos()
  {
    return posEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPos_Value()
  {
    return (EAttribute)posEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFlt()
  {
    return fltEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFlt_Value()
  {
    return (EAttribute)fltEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getClr()
  {
    return clrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getClr_Value()
  {
    return (EAttribute)clrEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDisp()
  {
    return dispEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDisp_Value()
  {
    return (EAttribute)dispEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getVerAl()
  {
    return verAlEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVerAl_Value()
  {
    return (EAttribute)verAlEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOFlow()
  {
    return oFlowEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getOFlow_Value()
  {
    return (EAttribute)oFlowEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWid()
  {
    return widEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWid_Value()
  {
    return (EReference)widEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getH8()
  {
    return h8EClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getH8_Value()
  {
    return (EReference)h8EClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCoord()
  {
    return coordEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCoord_Value()
  {
    return (EReference)coordEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMarg()
  {
    return margEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMarg_Value()
  {
    return (EReference)margEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPadd()
  {
    return paddEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPadd_Value()
  {
    return (EReference)paddEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMinMaxValue()
  {
    return minMaxValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMinMaxValue_MinVal()
  {
    return (EReference)minMaxValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMinMaxValue_MaxVal()
  {
    return (EReference)minMaxValueEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMinMaxValue_MidVal()
  {
    return (EReference)minMaxValueEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMinVal()
  {
    return minValEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMinVal_Value()
  {
    return (EAttribute)minValEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMinVal_MeasureType()
  {
    return (EAttribute)minValEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMaxVal()
  {
    return maxValEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMaxVal_Value()
  {
    return (EAttribute)maxValEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMaxVal_MeasureType()
  {
    return (EAttribute)maxValEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMidVal()
  {
    return midValEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMidVal_Value()
  {
    return (EAttribute)midValEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMidVal_MeasureType()
  {
    return (EAttribute)midValEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFourAspect()
  {
    return fourAspectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFourAspect_Left()
  {
    return (EReference)fourAspectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFourAspect_Right()
  {
    return (EReference)fourAspectEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFourAspect_Up()
  {
    return (EReference)fourAspectEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFourAspect_Down()
  {
    return (EReference)fourAspectEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getLeftAspect()
  {
    return leftAspectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getLeftAspect_Value()
  {
    return (EAttribute)leftAspectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getLeftAspect_MeasureType()
  {
    return (EAttribute)leftAspectEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRightAspect()
  {
    return rightAspectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRightAspect_Value()
  {
    return (EAttribute)rightAspectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRightAspect_MeasureType()
  {
    return (EAttribute)rightAspectEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getUpAspect()
  {
    return upAspectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUpAspect_Value()
  {
    return (EAttribute)upAspectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getUpAspect_MeasureType()
  {
    return (EAttribute)upAspectEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDownAspect()
  {
    return downAspectEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDownAspect_Value()
  {
    return (EAttribute)downAspectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDownAspect_MeasureType()
  {
    return (EAttribute)downAspectEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getPosVals()
  {
    return posValsEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getFltVals()
  {
    return fltValsEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getClrVals()
  {
    return clrValsEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getDispVals()
  {
    return dispValsEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getVeralVals()
  {
    return veralValsEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getOFlowVals()
  {
    return oFlowValsEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getInnerTypeArray()
  {
    return innerTypeArrayEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyUiDslFactory getMyUiDslFactory()
  {
    return (MyUiDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__HEADS);
    createEReference(modelEClass, MODEL__BODIS);
    createEReference(modelEClass, MODEL__ACCESSORIES);

    headEClass = createEClass(HEAD);
    createEAttribute(headEClass, HEAD__FILE_NAME);
    createEAttribute(headEClass, HEAD__HEAD_TYPE);

    bodyEClass = createEClass(BODY);
    createEReference(bodyEClass, BODY__NAME);
    createEReference(bodyEClass, BODY__RIGHT);
    createEReference(bodyEClass, BODY__SELF_REPEAT);

    nodeEClass = createEClass(NODE);
    createEAttribute(nodeEClass, NODE__NAME);

    selfRepeatEClass = createEClass(SELF_REPEAT);
    createEAttribute(selfRepeatEClass, SELF_REPEAT__NUMBER);
    createEAttribute(selfRepeatEClass, SELF_REPEAT__VERTICAL);

    accessoryEClass = createEClass(ACCESSORY);
    createEReference(accessoryEClass, ACCESSORY__LEFT);
    createEReference(accessoryEClass, ACCESSORY__TEXT);
    createEReference(accessoryEClass, ACCESSORY__STYLE);
    createEReference(accessoryEClass, ACCESSORY__CLAZZ);
    createEReference(accessoryEClass, ACCESSORY__TYPE);
    createEReference(accessoryEClass, ACCESSORY__FEATURE);

    innerFeatureEClass = createEClass(INNER_FEATURE);
    createEAttribute(innerFeatureEClass, INNER_FEATURE__VALUE);

    innerTextEClass = createEClass(INNER_TEXT);
    createEAttribute(innerTextEClass, INNER_TEXT__VALUE);

    innerStyleEClass = createEClass(INNER_STYLE);
    createEReference(innerStyleEClass, INNER_STYLE__STYLES);

    innerClassEClass = createEClass(INNER_CLASS);
    createEReference(innerClassEClass, INNER_CLASS__CLAZZES);

    classNameEClass = createEClass(CLASS_NAME);
    createEAttribute(classNameEClass, CLASS_NAME__THE_ID);
    createEReference(classNameEClass, CLASS_NAME__CLAZZ);

    classNameSecEClass = createEClass(CLASS_NAME_SEC);
    createEAttribute(classNameSecEClass, CLASS_NAME_SEC__CF_CLAZZ);

    innerTypeEClass = createEClass(INNER_TYPE);
    createEAttribute(innerTypeEClass, INNER_TYPE__VALUE);

    cssStylesEClass = createEClass(CSS_STYLES);
    createEReference(cssStylesEClass, CSS_STYLES__STYLES);

    cssStyleEClass = createEClass(CSS_STYLE);

    borderEClass = createEClass(BORDER);
    createEReference(borderEClass, BORDER__VALUE);

    colorEClass = createEClass(COLOR);
    createEReference(colorEClass, COLOR__VALUE);

    backColorEClass = createEClass(BACK_COLOR);
    createEReference(backColorEClass, BACK_COLOR__VALUE);

    colorDefEClass = createEClass(COLOR_DEF);

    literalColorEClass = createEClass(LITERAL_COLOR);
    createEAttribute(literalColorEClass, LITERAL_COLOR__VALUE);

    rgbaColorEClass = createEClass(RGBA_COLOR);
    createEReference(rgbaColorEClass, RGBA_COLOR__RVAL);
    createEReference(rgbaColorEClass, RGBA_COLOR__GVAL);
    createEReference(rgbaColorEClass, RGBA_COLOR__BVAL);
    createEReference(rgbaColorEClass, RGBA_COLOR__AVAL);

    rvalEClass = createEClass(RVAL);
    createEAttribute(rvalEClass, RVAL__VALUE);

    gvalEClass = createEClass(GVAL);
    createEAttribute(gvalEClass, GVAL__VALUE);

    bvalEClass = createEClass(BVAL);
    createEAttribute(bvalEClass, BVAL__VALUE);

    avalEClass = createEClass(AVAL);
    createEAttribute(avalEClass, AVAL__VALUE);

    borderRadEClass = createEClass(BORDER_RAD);
    createEAttribute(borderRadEClass, BORDER_RAD__VALUE);
    createEAttribute(borderRadEClass, BORDER_RAD__MEASURE_TYPE);

    posEClass = createEClass(POS);
    createEAttribute(posEClass, POS__VALUE);

    fltEClass = createEClass(FLT);
    createEAttribute(fltEClass, FLT__VALUE);

    clrEClass = createEClass(CLR);
    createEAttribute(clrEClass, CLR__VALUE);

    dispEClass = createEClass(DISP);
    createEAttribute(dispEClass, DISP__VALUE);

    verAlEClass = createEClass(VER_AL);
    createEAttribute(verAlEClass, VER_AL__VALUE);

    oFlowEClass = createEClass(OFLOW);
    createEAttribute(oFlowEClass, OFLOW__VALUE);

    widEClass = createEClass(WID);
    createEReference(widEClass, WID__VALUE);

    h8EClass = createEClass(H8);
    createEReference(h8EClass, H8__VALUE);

    coordEClass = createEClass(COORD);
    createEReference(coordEClass, COORD__VALUE);

    margEClass = createEClass(MARG);
    createEReference(margEClass, MARG__VALUE);

    paddEClass = createEClass(PADD);
    createEReference(paddEClass, PADD__VALUE);

    minMaxValueEClass = createEClass(MIN_MAX_VALUE);
    createEReference(minMaxValueEClass, MIN_MAX_VALUE__MIN_VAL);
    createEReference(minMaxValueEClass, MIN_MAX_VALUE__MAX_VAL);
    createEReference(minMaxValueEClass, MIN_MAX_VALUE__MID_VAL);

    minValEClass = createEClass(MIN_VAL);
    createEAttribute(minValEClass, MIN_VAL__VALUE);
    createEAttribute(minValEClass, MIN_VAL__MEASURE_TYPE);

    maxValEClass = createEClass(MAX_VAL);
    createEAttribute(maxValEClass, MAX_VAL__VALUE);
    createEAttribute(maxValEClass, MAX_VAL__MEASURE_TYPE);

    midValEClass = createEClass(MID_VAL);
    createEAttribute(midValEClass, MID_VAL__VALUE);
    createEAttribute(midValEClass, MID_VAL__MEASURE_TYPE);

    fourAspectEClass = createEClass(FOUR_ASPECT);
    createEReference(fourAspectEClass, FOUR_ASPECT__LEFT);
    createEReference(fourAspectEClass, FOUR_ASPECT__RIGHT);
    createEReference(fourAspectEClass, FOUR_ASPECT__UP);
    createEReference(fourAspectEClass, FOUR_ASPECT__DOWN);

    leftAspectEClass = createEClass(LEFT_ASPECT);
    createEAttribute(leftAspectEClass, LEFT_ASPECT__VALUE);
    createEAttribute(leftAspectEClass, LEFT_ASPECT__MEASURE_TYPE);

    rightAspectEClass = createEClass(RIGHT_ASPECT);
    createEAttribute(rightAspectEClass, RIGHT_ASPECT__VALUE);
    createEAttribute(rightAspectEClass, RIGHT_ASPECT__MEASURE_TYPE);

    upAspectEClass = createEClass(UP_ASPECT);
    createEAttribute(upAspectEClass, UP_ASPECT__VALUE);
    createEAttribute(upAspectEClass, UP_ASPECT__MEASURE_TYPE);

    downAspectEClass = createEClass(DOWN_ASPECT);
    createEAttribute(downAspectEClass, DOWN_ASPECT__VALUE);
    createEAttribute(downAspectEClass, DOWN_ASPECT__MEASURE_TYPE);

    // Create enums
    posValsEEnum = createEEnum(POS_VALS);
    fltValsEEnum = createEEnum(FLT_VALS);
    clrValsEEnum = createEEnum(CLR_VALS);
    dispValsEEnum = createEEnum(DISP_VALS);
    veralValsEEnum = createEEnum(VERAL_VALS);
    oFlowValsEEnum = createEEnum(OFLOW_VALS);
    innerTypeArrayEEnum = createEEnum(INNER_TYPE_ARRAY);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    borderEClass.getESuperTypes().add(this.getCssStyle());
    colorEClass.getESuperTypes().add(this.getCssStyle());
    backColorEClass.getESuperTypes().add(this.getCssStyle());
    literalColorEClass.getESuperTypes().add(this.getcolorDef());
    rgbaColorEClass.getESuperTypes().add(this.getcolorDef());
    borderRadEClass.getESuperTypes().add(this.getCssStyle());
    posEClass.getESuperTypes().add(this.getCssStyle());
    fltEClass.getESuperTypes().add(this.getCssStyle());
    clrEClass.getESuperTypes().add(this.getCssStyle());
    dispEClass.getESuperTypes().add(this.getCssStyle());
    verAlEClass.getESuperTypes().add(this.getCssStyle());
    oFlowEClass.getESuperTypes().add(this.getCssStyle());
    widEClass.getESuperTypes().add(this.getCssStyle());
    h8EClass.getESuperTypes().add(this.getCssStyle());
    coordEClass.getESuperTypes().add(this.getCssStyle());
    margEClass.getESuperTypes().add(this.getCssStyle());
    paddEClass.getESuperTypes().add(this.getCssStyle());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Heads(), this.getHead(), null, "heads", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Bodis(), this.getBody(), null, "bodis", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_Accessories(), this.getAccessory(), null, "accessories", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(headEClass, Head.class, "Head", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getHead_FileName(), ecorePackage.getEString(), "fileName", null, 0, 1, Head.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getHead_HeadType(), ecorePackage.getEString(), "headType", null, 0, 1, Head.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(bodyEClass, Body.class, "Body", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBody_Name(), this.getNode(), null, "name", null, 0, 1, Body.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBody_Right(), this.getNode(), null, "right", null, 0, -1, Body.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBody_SelfRepeat(), this.getSelfRepeat(), null, "selfRepeat", null, 0, 1, Body.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(nodeEClass, Node.class, "Node", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNode_Name(), ecorePackage.getEChar(), "name", null, 0, 1, Node.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(selfRepeatEClass, SelfRepeat.class, "SelfRepeat", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSelfRepeat_Number(), ecorePackage.getEInt(), "number", null, 0, 1, SelfRepeat.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSelfRepeat_Vertical(), ecorePackage.getEBoolean(), "vertical", null, 0, 1, SelfRepeat.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(accessoryEClass, Accessory.class, "Accessory", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAccessory_Left(), this.getNode(), null, "left", null, 0, 1, Accessory.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAccessory_Text(), this.getInnerText(), null, "text", null, 0, 1, Accessory.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAccessory_Style(), this.getInnerStyle(), null, "style", null, 0, 1, Accessory.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAccessory_Clazz(), this.getInnerClass(), null, "clazz", null, 0, 1, Accessory.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAccessory_Type(), this.getInnerType(), null, "type", null, 0, 1, Accessory.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAccessory_Feature(), this.getInnerFeature(), null, "feature", null, 0, 1, Accessory.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(innerFeatureEClass, InnerFeature.class, "InnerFeature", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInnerFeature_Value(), ecorePackage.getEString(), "value", null, 0, 1, InnerFeature.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(innerTextEClass, InnerText.class, "InnerText", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInnerText_Value(), ecorePackage.getEString(), "value", null, 0, 1, InnerText.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(innerStyleEClass, InnerStyle.class, "InnerStyle", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInnerStyle_Styles(), this.getCssStyle(), null, "styles", null, 0, -1, InnerStyle.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(innerClassEClass, InnerClass.class, "InnerClass", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInnerClass_Clazzes(), this.getClassName(), null, "clazzes", null, 0, 1, InnerClass.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(classNameEClass, ClassName.class, "ClassName", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getClassName_TheId(), ecorePackage.getEString(), "theId", null, 0, 1, ClassName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getClassName_Clazz(), this.getClassNameSec(), null, "clazz", null, 0, -1, ClassName.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(classNameSecEClass, ClassNameSec.class, "ClassNameSec", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getClassNameSec_CfClazz(), ecorePackage.getEString(), "cfClazz", null, 0, 1, ClassNameSec.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(innerTypeEClass, InnerType.class, "InnerType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInnerType_Value(), this.getInnerTypeArray(), "value", null, 0, 1, InnerType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(cssStylesEClass, CssStyles.class, "CssStyles", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCssStyles_Styles(), this.getCssStyle(), null, "styles", null, 0, 1, CssStyles.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(cssStyleEClass, CssStyle.class, "CssStyle", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(borderEClass, Border.class, "Border", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBorder_Value(), this.getcolorDef(), null, "value", null, 0, 1, Border.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(colorEClass, Color.class, "Color", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getColor_Value(), this.getcolorDef(), null, "value", null, 0, 1, Color.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(backColorEClass, BackColor.class, "BackColor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBackColor_Value(), this.getcolorDef(), null, "value", null, 0, 1, BackColor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(colorDefEClass, colorDef.class, "colorDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(literalColorEClass, LiteralColor.class, "LiteralColor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLiteralColor_Value(), ecorePackage.getEString(), "value", null, 0, 1, LiteralColor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rgbaColorEClass, RgbaColor.class, "RgbaColor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRgbaColor_Rval(), this.getRval(), null, "rval", null, 0, 1, RgbaColor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRgbaColor_Gval(), this.getGval(), null, "gval", null, 0, 1, RgbaColor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRgbaColor_Bval(), this.getBval(), null, "bval", null, 0, 1, RgbaColor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRgbaColor_Aval(), this.getAval(), null, "aval", null, 0, 1, RgbaColor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rvalEClass, Rval.class, "Rval", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRval_Value(), ecorePackage.getEInt(), "value", null, 0, 1, Rval.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(gvalEClass, Gval.class, "Gval", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGval_Value(), ecorePackage.getEInt(), "value", null, 0, 1, Gval.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(bvalEClass, Bval.class, "Bval", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBval_Value(), ecorePackage.getEInt(), "value", null, 0, 1, Bval.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(avalEClass, Aval.class, "Aval", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAval_Value(), ecorePackage.getEInt(), "value", null, 0, 1, Aval.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(borderRadEClass, BorderRad.class, "BorderRad", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBorderRad_Value(), ecorePackage.getEInt(), "value", null, 0, 1, BorderRad.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBorderRad_MeasureType(), ecorePackage.getEString(), "measureType", null, 0, 1, BorderRad.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(posEClass, Pos.class, "Pos", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPos_Value(), this.getPosVals(), "value", null, 0, 1, Pos.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fltEClass, Flt.class, "Flt", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFlt_Value(), this.getFltVals(), "value", null, 0, 1, Flt.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(clrEClass, Clr.class, "Clr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getClr_Value(), this.getClrVals(), "value", null, 0, 1, Clr.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dispEClass, Disp.class, "Disp", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDisp_Value(), this.getDispVals(), "value", null, 0, 1, Disp.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(verAlEClass, VerAl.class, "VerAl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVerAl_Value(), this.getVeralVals(), "value", null, 0, 1, VerAl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(oFlowEClass, OFlow.class, "OFlow", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOFlow_Value(), this.getOFlowVals(), "value", null, 0, 1, OFlow.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(widEClass, Wid.class, "Wid", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getWid_Value(), this.getMinMaxValue(), null, "value", null, 0, 1, Wid.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(h8EClass, edu.aut.islab.ghaemi.minuy.myUiDsl.H8.class, "H8", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getH8_Value(), this.getMinMaxValue(), null, "value", null, 0, 1, edu.aut.islab.ghaemi.minuy.myUiDsl.H8.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(coordEClass, Coord.class, "Coord", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCoord_Value(), this.getFourAspect(), null, "value", null, 0, 1, Coord.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(margEClass, Marg.class, "Marg", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMarg_Value(), this.getFourAspect(), null, "value", null, 0, 1, Marg.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(paddEClass, Padd.class, "Padd", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPadd_Value(), this.getFourAspect(), null, "value", null, 0, 1, Padd.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(minMaxValueEClass, MinMaxValue.class, "MinMaxValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMinMaxValue_MinVal(), this.getMinVal(), null, "minVal", null, 0, 1, MinMaxValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMinMaxValue_MaxVal(), this.getMaxVal(), null, "maxVal", null, 0, 1, MinMaxValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMinMaxValue_MidVal(), this.getMidVal(), null, "midVal", null, 0, 1, MinMaxValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(minValEClass, MinVal.class, "MinVal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMinVal_Value(), ecorePackage.getEInt(), "value", null, 0, 1, MinVal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMinVal_MeasureType(), ecorePackage.getEString(), "measureType", null, 0, 1, MinVal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(maxValEClass, MaxVal.class, "MaxVal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMaxVal_Value(), ecorePackage.getEInt(), "value", null, 0, 1, MaxVal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMaxVal_MeasureType(), ecorePackage.getEString(), "measureType", null, 0, 1, MaxVal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(midValEClass, MidVal.class, "MidVal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMidVal_Value(), ecorePackage.getEInt(), "value", null, 0, 1, MidVal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMidVal_MeasureType(), ecorePackage.getEString(), "measureType", null, 0, 1, MidVal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fourAspectEClass, FourAspect.class, "FourAspect", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFourAspect_Left(), this.getLeftAspect(), null, "left", null, 0, 1, FourAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFourAspect_Right(), this.getRightAspect(), null, "right", null, 0, 1, FourAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFourAspect_Up(), this.getUpAspect(), null, "up", null, 0, 1, FourAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFourAspect_Down(), this.getDownAspect(), null, "down", null, 0, 1, FourAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(leftAspectEClass, LeftAspect.class, "LeftAspect", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLeftAspect_Value(), ecorePackage.getEInt(), "value", null, 0, 1, LeftAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLeftAspect_MeasureType(), ecorePackage.getEString(), "measureType", null, 0, 1, LeftAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rightAspectEClass, RightAspect.class, "RightAspect", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRightAspect_Value(), ecorePackage.getEInt(), "value", null, 0, 1, RightAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRightAspect_MeasureType(), ecorePackage.getEString(), "measureType", null, 0, 1, RightAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(upAspectEClass, UpAspect.class, "UpAspect", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUpAspect_Value(), ecorePackage.getEInt(), "value", null, 0, 1, UpAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUpAspect_MeasureType(), ecorePackage.getEString(), "measureType", null, 0, 1, UpAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(downAspectEClass, DownAspect.class, "DownAspect", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDownAspect_Value(), ecorePackage.getEInt(), "value", null, 0, 1, DownAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDownAspect_MeasureType(), ecorePackage.getEString(), "measureType", null, 0, 1, DownAspect.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(posValsEEnum, PosVals.class, "PosVals");
    addEEnumLiteral(posValsEEnum, PosVals.STATIC);
    addEEnumLiteral(posValsEEnum, PosVals.RELATIVE);
    addEEnumLiteral(posValsEEnum, PosVals.FIXED);
    addEEnumLiteral(posValsEEnum, PosVals.ABSOLUTE);
    addEEnumLiteral(posValsEEnum, PosVals.STEAKY);

    initEEnum(fltValsEEnum, FltVals.class, "FltVals");
    addEEnumLiteral(fltValsEEnum, FltVals.LEFT);
    addEEnumLiteral(fltValsEEnum, FltVals.RIGHT);
    addEEnumLiteral(fltValsEEnum, FltVals.NONE);
    addEEnumLiteral(fltValsEEnum, FltVals.START);
    addEEnumLiteral(fltValsEEnum, FltVals.END);

    initEEnum(clrValsEEnum, ClrVals.class, "ClrVals");
    addEEnumLiteral(clrValsEEnum, ClrVals.LEFT);
    addEEnumLiteral(clrValsEEnum, ClrVals.RIGHT);
    addEEnumLiteral(clrValsEEnum, ClrVals.BOTH);
    addEEnumLiteral(clrValsEEnum, ClrVals.NONE);

    initEEnum(dispValsEEnum, DispVals.class, "DispVals");
    addEEnumLiteral(dispValsEEnum, DispVals.BLOCK);
    addEEnumLiteral(dispValsEEnum, DispVals.INLINE);
    addEEnumLiteral(dispValsEEnum, DispVals.IN_BL);
    addEEnumLiteral(dispValsEEnum, DispVals.TABLE);
    addEEnumLiteral(dispValsEEnum, DispVals.NONE);

    initEEnum(veralValsEEnum, VeralVals.class, "VeralVals");
    addEEnumLiteral(veralValsEEnum, VeralVals.TOP);
    addEEnumLiteral(veralValsEEnum, VeralVals.DOWN);
    addEEnumLiteral(veralValsEEnum, VeralVals.CENTER);

    initEEnum(oFlowValsEEnum, OFlowVals.class, "OFlowVals");
    addEEnumLiteral(oFlowValsEEnum, OFlowVals.SCROLL);
    addEEnumLiteral(oFlowValsEEnum, OFlowVals.VISIBLE);
    addEEnumLiteral(oFlowValsEEnum, OFlowVals.HIDDEN);
    addEEnumLiteral(oFlowValsEEnum, OFlowVals.AUTO);

    initEEnum(innerTypeArrayEEnum, InnerTypeArray.class, "InnerTypeArray");
    addEEnumLiteral(innerTypeArrayEEnum, InnerTypeArray.DIV);
    addEEnumLiteral(innerTypeArrayEEnum, InnerTypeArray.PARA);
    addEEnumLiteral(innerTypeArrayEEnum, InnerTypeArray.INPUT);
    addEEnumLiteral(innerTypeArrayEEnum, InnerTypeArray.TABLE);
    addEEnumLiteral(innerTypeArrayEEnum, InnerTypeArray.TR);
    addEEnumLiteral(innerTypeArrayEEnum, InnerTypeArray.TD);
    addEEnumLiteral(innerTypeArrayEEnum, InnerTypeArray.IMG);
    addEEnumLiteral(innerTypeArrayEEnum, InnerTypeArray.FORM);
    addEEnumLiteral(innerTypeArrayEEnum, InnerTypeArray.BUTTON);

    // Create resource
    createResource(eNS_URI);
  }

} //MyUiDslPackageImpl
