/*
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyUiDslStandaloneSetup extends MyUiDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MyUiDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
