/*
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyUiDslRuntimeModule extends AbstractMyUiDslRuntimeModule {
}
