/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.generator;

import com.google.common.collect.Iterators;
import edu.aut.islab.ghaemi.minuy.generator.model.OriginateTwo;
import edu.aut.islab.ghaemi.minuy.generator.model.UNode;
import edu.aut.islab.ghaemi.minuy.generator.model.UNodeHtml;
import edu.aut.islab.ghaemi.minuy.myUiDsl.Model;
import java.util.ArrayList;
import java.util.Iterator;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyUiDslGenerator extends AbstractGenerator {
  private int num = 0;
  
  private String stra = "lopj.txt";
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    URI _normalizedURI = EcoreUtil2.getNormalizedURI(resource);
    OriginateTwo.setUri(_normalizedURI);
    OriginateTwo.setRes(resource);
    ArrayList<String> _cssz = OriginateTwo.getCssz();
    _cssz.clear();
    ArrayList<String> _jssz = OriginateTwo.getJssz();
    _jssz.clear();
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterator<Model> _filter = Iterators.<Model>filter(_allContents, Model.class);
    final Procedure1<Model> _function = (Model it) -> {
      OriginateTwo.CompileModel(it);
    };
    IteratorExtensions.<Model>forEach(_filter, _function);
    UNode _root = UNode.getRoot();
    String _compile = UNodeHtml.compile(_root);
    final String code = _compile.toString();
    URI _normalizedURI_1 = EcoreUtil2.getNormalizedURI(resource);
    String _lastSegment = _normalizedURI_1.lastSegment();
    String _replace = _lastSegment.replace(".myui", ".html");
    ArrayList<String> _cssz_1 = OriginateTwo.getCssz();
    ArrayList<String> _jssz_1 = OriginateTwo.getJssz();
    String _produceFinalHtml = UNodeHtml.produceFinalHtml(_cssz_1, _jssz_1, code);
    fsa.generateFile(_replace, _produceFinalHtml);
  }
}
