/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy;

import edu.aut.islab.ghaemi.minuy.AbstractMyUiDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyUiDslRuntimeModule extends AbstractMyUiDslRuntimeModule {
}
