/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.myUiDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Accessory</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getLeft <em>Left</em>}</li>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getText <em>Text</em>}</li>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getStyle <em>Style</em>}</li>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getClazz <em>Clazz</em>}</li>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getType <em>Type</em>}</li>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getAccessory()
 * @model
 * @generated
 */
public interface Accessory extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Node)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getAccessory_Left()
   * @model containment="true"
   * @generated
   */
  Node getLeft();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Node value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(InnerText)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getAccessory_Text()
   * @model containment="true"
   * @generated
   */
  InnerText getText();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(InnerText value);

  /**
   * Returns the value of the '<em><b>Style</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Style</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Style</em>' containment reference.
   * @see #setStyle(InnerStyle)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getAccessory_Style()
   * @model containment="true"
   * @generated
   */
  InnerStyle getStyle();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getStyle <em>Style</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Style</em>' containment reference.
   * @see #getStyle()
   * @generated
   */
  void setStyle(InnerStyle value);

  /**
   * Returns the value of the '<em><b>Clazz</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Clazz</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clazz</em>' containment reference.
   * @see #setClazz(InnerClass)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getAccessory_Clazz()
   * @model containment="true"
   * @generated
   */
  InnerClass getClazz();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getClazz <em>Clazz</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clazz</em>' containment reference.
   * @see #getClazz()
   * @generated
   */
  void setClazz(InnerClass value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(InnerType)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getAccessory_Type()
   * @model containment="true"
   * @generated
   */
  InnerType getType();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(InnerType value);

  /**
   * Returns the value of the '<em><b>Feature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' containment reference.
   * @see #setFeature(InnerFeature)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getAccessory_Feature()
   * @model containment="true"
   * @generated
   */
  InnerFeature getFeature();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Accessory#getFeature <em>Feature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature</em>' containment reference.
   * @see #getFeature()
   * @generated
   */
  void setFeature(InnerFeature value);

} // Accessory
