/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.myUiDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Clr#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getClr()
 * @model
 * @generated
 */
public interface Clr extends CssStyle
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link edu.aut.islab.ghaemi.minuy.myUiDsl.ClrVals}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.ClrVals
   * @see #setValue(ClrVals)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getClr_Value()
   * @model
   * @generated
   */
  ClrVals getValue();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.Clr#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.ClrVals
   * @see #getValue()
   * @generated
   */
  void setValue(ClrVals value);

} // Clr
