/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.myUiDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Four Aspect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.FourAspect#getLeft <em>Left</em>}</li>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.FourAspect#getRight <em>Right</em>}</li>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.FourAspect#getUp <em>Up</em>}</li>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.FourAspect#getDown <em>Down</em>}</li>
 * </ul>
 *
 * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getFourAspect()
 * @model
 * @generated
 */
public interface FourAspect extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(LeftAspect)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getFourAspect_Left()
   * @model containment="true"
   * @generated
   */
  LeftAspect getLeft();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.FourAspect#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(LeftAspect value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(RightAspect)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getFourAspect_Right()
   * @model containment="true"
   * @generated
   */
  RightAspect getRight();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.FourAspect#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(RightAspect value);

  /**
   * Returns the value of the '<em><b>Up</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Up</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Up</em>' containment reference.
   * @see #setUp(UpAspect)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getFourAspect_Up()
   * @model containment="true"
   * @generated
   */
  UpAspect getUp();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.FourAspect#getUp <em>Up</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Up</em>' containment reference.
   * @see #getUp()
   * @generated
   */
  void setUp(UpAspect value);

  /**
   * Returns the value of the '<em><b>Down</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Down</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Down</em>' containment reference.
   * @see #setDown(DownAspect)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getFourAspect_Down()
   * @model containment="true"
   * @generated
   */
  DownAspect getDown();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.FourAspect#getDown <em>Down</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Down</em>' containment reference.
   * @see #getDown()
   * @generated
   */
  void setDown(DownAspect value);

} // FourAspect
