/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.myUiDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inner Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.InnerType#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getInnerType()
 * @model
 * @generated
 */
public interface InnerType extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * The literals are from the enumeration {@link edu.aut.islab.ghaemi.minuy.myUiDsl.InnerTypeArray}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.InnerTypeArray
   * @see #setValue(InnerTypeArray)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getInnerType_Value()
   * @model
   * @generated
   */
  InnerTypeArray getValue();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.InnerType#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.InnerTypeArray
   * @see #getValue()
   * @generated
   */
  void setValue(InnerTypeArray value);

} // InnerType
