/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.myUiDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inner Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.InnerClass#getClazzes <em>Clazzes</em>}</li>
 * </ul>
 *
 * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getInnerClass()
 * @model
 * @generated
 */
public interface InnerClass extends EObject
{
  /**
   * Returns the value of the '<em><b>Clazzes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Clazzes</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clazzes</em>' containment reference.
   * @see #setClazzes(ClassName)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getInnerClass_Clazzes()
   * @model containment="true"
   * @generated
   */
  ClassName getClazzes();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.InnerClass#getClazzes <em>Clazzes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clazzes</em>' containment reference.
   * @see #getClazzes()
   * @generated
   */
  void setClazzes(ClassName value);

} // InnerClass
