/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.myUiDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage
 * @generated
 */
public interface MyUiDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyUiDslFactory eINSTANCE = edu.aut.islab.ghaemi.minuy.myUiDsl.impl.MyUiDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Head</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Head</em>'.
   * @generated
   */
  Head createHead();

  /**
   * Returns a new object of class '<em>Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Body</em>'.
   * @generated
   */
  Body createBody();

  /**
   * Returns a new object of class '<em>Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Node</em>'.
   * @generated
   */
  Node createNode();

  /**
   * Returns a new object of class '<em>Self Repeat</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Self Repeat</em>'.
   * @generated
   */
  SelfRepeat createSelfRepeat();

  /**
   * Returns a new object of class '<em>Accessory</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Accessory</em>'.
   * @generated
   */
  Accessory createAccessory();

  /**
   * Returns a new object of class '<em>Inner Feature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inner Feature</em>'.
   * @generated
   */
  InnerFeature createInnerFeature();

  /**
   * Returns a new object of class '<em>Inner Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inner Text</em>'.
   * @generated
   */
  InnerText createInnerText();

  /**
   * Returns a new object of class '<em>Inner Style</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inner Style</em>'.
   * @generated
   */
  InnerStyle createInnerStyle();

  /**
   * Returns a new object of class '<em>Inner Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inner Class</em>'.
   * @generated
   */
  InnerClass createInnerClass();

  /**
   * Returns a new object of class '<em>Class Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Name</em>'.
   * @generated
   */
  ClassName createClassName();

  /**
   * Returns a new object of class '<em>Class Name Sec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Name Sec</em>'.
   * @generated
   */
  ClassNameSec createClassNameSec();

  /**
   * Returns a new object of class '<em>Inner Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inner Type</em>'.
   * @generated
   */
  InnerType createInnerType();

  /**
   * Returns a new object of class '<em>Css Styles</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Css Styles</em>'.
   * @generated
   */
  CssStyles createCssStyles();

  /**
   * Returns a new object of class '<em>Css Style</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Css Style</em>'.
   * @generated
   */
  CssStyle createCssStyle();

  /**
   * Returns a new object of class '<em>Border</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Border</em>'.
   * @generated
   */
  Border createBorder();

  /**
   * Returns a new object of class '<em>Color</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Color</em>'.
   * @generated
   */
  Color createColor();

  /**
   * Returns a new object of class '<em>Back Color</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Back Color</em>'.
   * @generated
   */
  BackColor createBackColor();

  /**
   * Returns a new object of class '<em>color Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>color Def</em>'.
   * @generated
   */
  colorDef createcolorDef();

  /**
   * Returns a new object of class '<em>Literal Color</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Literal Color</em>'.
   * @generated
   */
  LiteralColor createLiteralColor();

  /**
   * Returns a new object of class '<em>Rgba Color</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rgba Color</em>'.
   * @generated
   */
  RgbaColor createRgbaColor();

  /**
   * Returns a new object of class '<em>Rval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rval</em>'.
   * @generated
   */
  Rval createRval();

  /**
   * Returns a new object of class '<em>Gval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gval</em>'.
   * @generated
   */
  Gval createGval();

  /**
   * Returns a new object of class '<em>Bval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bval</em>'.
   * @generated
   */
  Bval createBval();

  /**
   * Returns a new object of class '<em>Aval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Aval</em>'.
   * @generated
   */
  Aval createAval();

  /**
   * Returns a new object of class '<em>Border Rad</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Border Rad</em>'.
   * @generated
   */
  BorderRad createBorderRad();

  /**
   * Returns a new object of class '<em>Pos</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pos</em>'.
   * @generated
   */
  Pos createPos();

  /**
   * Returns a new object of class '<em>Flt</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flt</em>'.
   * @generated
   */
  Flt createFlt();

  /**
   * Returns a new object of class '<em>Clr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Clr</em>'.
   * @generated
   */
  Clr createClr();

  /**
   * Returns a new object of class '<em>Disp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Disp</em>'.
   * @generated
   */
  Disp createDisp();

  /**
   * Returns a new object of class '<em>Ver Al</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ver Al</em>'.
   * @generated
   */
  VerAl createVerAl();

  /**
   * Returns a new object of class '<em>OFlow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>OFlow</em>'.
   * @generated
   */
  OFlow createOFlow();

  /**
   * Returns a new object of class '<em>Wid</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Wid</em>'.
   * @generated
   */
  Wid createWid();

  /**
   * Returns a new object of class '<em>H8</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>H8</em>'.
   * @generated
   */
  H8 createH8();

  /**
   * Returns a new object of class '<em>Coord</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Coord</em>'.
   * @generated
   */
  Coord createCoord();

  /**
   * Returns a new object of class '<em>Marg</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Marg</em>'.
   * @generated
   */
  Marg createMarg();

  /**
   * Returns a new object of class '<em>Padd</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Padd</em>'.
   * @generated
   */
  Padd createPadd();

  /**
   * Returns a new object of class '<em>Min Max Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Min Max Value</em>'.
   * @generated
   */
  MinMaxValue createMinMaxValue();

  /**
   * Returns a new object of class '<em>Min Val</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Min Val</em>'.
   * @generated
   */
  MinVal createMinVal();

  /**
   * Returns a new object of class '<em>Max Val</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Max Val</em>'.
   * @generated
   */
  MaxVal createMaxVal();

  /**
   * Returns a new object of class '<em>Mid Val</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mid Val</em>'.
   * @generated
   */
  MidVal createMidVal();

  /**
   * Returns a new object of class '<em>Four Aspect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Four Aspect</em>'.
   * @generated
   */
  FourAspect createFourAspect();

  /**
   * Returns a new object of class '<em>Left Aspect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Left Aspect</em>'.
   * @generated
   */
  LeftAspect createLeftAspect();

  /**
   * Returns a new object of class '<em>Right Aspect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Right Aspect</em>'.
   * @generated
   */
  RightAspect createRightAspect();

  /**
   * Returns a new object of class '<em>Up Aspect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Up Aspect</em>'.
   * @generated
   */
  UpAspect createUpAspect();

  /**
   * Returns a new object of class '<em>Down Aspect</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Down Aspect</em>'.
   * @generated
   */
  DownAspect createDownAspect();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyUiDslPackage getMyUiDslPackage();

} //MyUiDslFactory
