/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.myUiDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Pos Vals</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getPosVals()
 * @model
 * @generated
 */
public enum PosVals implements Enumerator
{
  /**
   * The '<em><b>Static</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STATIC_VALUE
   * @generated
   * @ordered
   */
  STATIC(0, "Static", "Static"),

  /**
   * The '<em><b>Relative</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RELATIVE_VALUE
   * @generated
   * @ordered
   */
  RELATIVE(1, "Relative", "Relative"),

  /**
   * The '<em><b>Fixed</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FIXED_VALUE
   * @generated
   * @ordered
   */
  FIXED(2, "Fixed", "Fixed"),

  /**
   * The '<em><b>Absolute</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ABSOLUTE_VALUE
   * @generated
   * @ordered
   */
  ABSOLUTE(3, "Absolute", "Absolute"),

  /**
   * The '<em><b>Steaky</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STEAKY_VALUE
   * @generated
   * @ordered
   */
  STEAKY(4, "Steaky", "Steaky");

  /**
   * The '<em><b>Static</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Static</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STATIC
   * @model name="Static"
   * @generated
   * @ordered
   */
  public static final int STATIC_VALUE = 0;

  /**
   * The '<em><b>Relative</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Relative</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RELATIVE
   * @model name="Relative"
   * @generated
   * @ordered
   */
  public static final int RELATIVE_VALUE = 1;

  /**
   * The '<em><b>Fixed</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Fixed</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FIXED
   * @model name="Fixed"
   * @generated
   * @ordered
   */
  public static final int FIXED_VALUE = 2;

  /**
   * The '<em><b>Absolute</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Absolute</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ABSOLUTE
   * @model name="Absolute"
   * @generated
   * @ordered
   */
  public static final int ABSOLUTE_VALUE = 3;

  /**
   * The '<em><b>Steaky</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Steaky</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STEAKY
   * @model name="Steaky"
   * @generated
   * @ordered
   */
  public static final int STEAKY_VALUE = 4;

  /**
   * An array of all the '<em><b>Pos Vals</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final PosVals[] VALUES_ARRAY =
    new PosVals[]
    {
      STATIC,
      RELATIVE,
      FIXED,
      ABSOLUTE,
      STEAKY,
    };

  /**
   * A public read-only list of all the '<em><b>Pos Vals</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<PosVals> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Pos Vals</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PosVals get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PosVals result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Pos Vals</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PosVals getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PosVals result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Pos Vals</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PosVals get(int value)
  {
    switch (value)
    {
      case STATIC_VALUE: return STATIC;
      case RELATIVE_VALUE: return RELATIVE;
      case FIXED_VALUE: return FIXED;
      case ABSOLUTE_VALUE: return ABSOLUTE;
      case STEAKY_VALUE: return STEAKY;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private PosVals(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //PosVals
