/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.myUiDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Self Repeat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.SelfRepeat#getNumber <em>Number</em>}</li>
 *   <li>{@link edu.aut.islab.ghaemi.minuy.myUiDsl.SelfRepeat#isVertical <em>Vertical</em>}</li>
 * </ul>
 *
 * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getSelfRepeat()
 * @model
 * @generated
 */
public interface SelfRepeat extends EObject
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getSelfRepeat_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.SelfRepeat#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

  /**
   * Returns the value of the '<em><b>Vertical</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vertical</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vertical</em>' attribute.
   * @see #setVertical(boolean)
   * @see edu.aut.islab.ghaemi.minuy.myUiDsl.MyUiDslPackage#getSelfRepeat_Vertical()
   * @model
   * @generated
   */
  boolean isVertical();

  /**
   * Sets the value of the '{@link edu.aut.islab.ghaemi.minuy.myUiDsl.SelfRepeat#isVertical <em>Vertical</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vertical</em>' attribute.
   * @see #isVertical()
   * @generated
   */
  void setVertical(boolean value);

} // SelfRepeat
