/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.ui.contentassist;

import edu.aut.islab.ghaemi.minuy.ui.contentassist.AbstractMyUiDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyUiDslProposalProvider extends AbstractMyUiDslProposalProvider {
}
