/**
 * generated by Xtext 2.10.0
 */
package edu.aut.islab.ghaemi.minuy.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class MyUiDslQuickfixProvider extends DefaultQuickfixProvider {
}
